version: '3'

services:
  nginx:
    build: build/nginx
    container_name: symfony-nginx
    volumes:
      - ./symfony/:/var/www/symfony/
    ports:
      - 8001:80
    networks:
      - symfony

  php:
    build:
      context: ./build/php
      dockerfile: Dockerfile
    container_name: symfony-php
    environment:
      APP_ENV: dev
      # DATABASE_URL: mysql://symfony_user:symfony_password@mysql:3306/symfony_db?serverVersion=5.7
    volumes:
      - ./symfony/:/var/www/symfony/
    networks:
      - symfony
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: symfony-mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./.data/db:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony:
